spring.datasource.url=jdbc:postgresql://db.lsduwztculsznmulbggj.supabase.co:5432/postgres
spring.datasource.username=postgres.lsduwztculsznmulbggj
spring.datasource.password=coletae125*/*!!78(78).,@+123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect